### ISSUE TITLE
How do we update the RN4870 firmware on the PIC-BLE module? 

### ISSUE THREAD

**Issue by orcad** [microchip-pic-avr-solutions/pic-lightblue-explorer-demo#3]
I know how to update the RN4870 firmware of PicTail board, but couldn't find the method to do that for the PIC-BLE module. The PIC-BLE baud rate is set to 9600 and that BR is not listed in the "isupdate.exe" application.

The RN4870 firmware of RN4870 for the PIC-BLE module is 1.3 right off the box and the latest is above 1.3 so how can we upgrade the firmware? 

Tera Term> RN4870 V1.30 3/18/2018 (c)Microchip Technology Inc

**Comment by orcad** [comment]
Also need quick method to change the BR on PIC-BLE module by firmware, not HW.

**Comment by zmaloy** [comment]
There are two BR in this firmware, which BR are you looking to adjust, the CDC_UART BR or the RN4870 UART BR?

**Comment by orcad** [comment]
The BR was reset to factory default of 115200 and I want to move it back to 9600. The BR can be reset by factory reset very easily but can not be put back to 9600 that easy. What is an easy way to put it back to 9600? Is there any firmware just to do that?


 

    On Tuesday, October 5, 2021, 02:06:43 p.m. EDT, zmaloy ***@***.***> wrote:  
 
 


There are two BR in this firmware, which BR are you looking to adjust, the CDC_UART BR or the RN4870 UART BR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zmaloy** [comment]
@orcad This issue has two pieces and therefore I'm am going to provide an answer in two parts. First I will address the firmware update portion:

## RN4870 firmware Update

### Example Firmware update code
There is available standalone firmware update code which provides an example of a host MCU updating BM71 firmware via UART. The firmware update process is the same for BM70/71 and RN4870/71. This code is written for PIC32 and can be leveraged to achieve the desired firmware update.

[Example Firmware update code Github](https://github.com/MchpBTApps/BM71_MemoryProgramming)

### Documentation
The complete process to execute a device firmware update (including the command set and command used) are provided in the document below.

[ BM70/71 Device Firmware Update Process User's Guide](https://ww1.microchip.com/downloads/en/DeviceDoc/50003134A.pdf)

### Example python code
There is also some python code which has been written to demystify the isupdate tool. 

[Python Github Page](https://github.com/KDonadio/RN4871-Test-Fixture)

This should provide you with ample resources to update the firmware of the RN4870 module.

## RN4870 Module Baud Rate Setting

If as you stated, the module was factory reset and the baud rate of the module itself is 115200. Then the MCU on the PIC-BLE board and the RN4870 are no longer able to communicate as the MCU UART setting for talking to the RN4870 is 9600 and the module itself is on 115200.

In order to correct this you will need to open this pic-lightblue-explorer-demo in MPLAB X IDE and launch MCC. 

Once MCC is loaded complete the following:
* In the project properties window navigate to Foundation Services -> UART
* In the FS UART window in the row for UART_BLE change the baud rate text entry to 115200
* Press the Generate button to generate the new settings
* Make and program the device

From here open a terminal program such as tera term with the respective COM port:
Settings - 9600 8-N-1
* In the terminal program type $$$ to enter command mode should see CMD> in the terminal indicating command mode
* Type SB,09 to set RN4870 module baud to 9600 | observe AOK response
* Type R,1 to reboot and apply changes | observe "rebooting" response

Follow the above MCC steps to set the UART_BLE baud rate back to 9600. The commands I listed are available in the [RN4870/RN4871 Bluetooth Low Energy Module User's Guide](http://ww1.microchip.com/downloads/en/DeviceDoc/50002466B.pdf) It is important to utilize this guide when executing these command and understand what the command is doing and how to utilize it. 
This will correct the BR isssue on the RN4870 module as you have stated.
